name: ayur_medi_care
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.7.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  http: ^0.13.5
  provider: ^6.0.4
  fluttertoast: ^8.1.1
  shared_preferences: ^2.0.15
  dropdown_button2: ^1.8.9
  image_picker: ^0.8.6
  multiple_search_selection: ^2.3.2

flutter:

  uses-material-design: true

  assets:
    - Assets/Images/


